#!/usr/bin/perl
use esmith::Build::CreateLinks qw(:all);

my $event = "nethserver-crontabmanager-update";
event_actions($event, 
'initialize-default-databases' => '00');

templates2events("/etc/crontab", $event);

event_services($event, 'crond' => 'restart');
