#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use JSON;
use NethServer::ApiTools;

my $input = NethServer::ApiTools::readInput();
my $cmd = $input->{'action'};

my $ret = {};

if ($cmd eq 'crontab') {

    my @crontab;
    my $db = esmith::ConfigDB->open_ro('crontab');
    foreach ($db->get_all_by_prop('type'=>'cron')) {
        my %props = $_->props();
        delete($props{'type'});
        $props{'name'} = $_->key;
        
        # for compatibility with nethgui module, 
        # the prop Every* is removed in the cockpit UI
        if ( ! $props{'Minute'} && ($props{'EveryMinute'} ne 'disabled' )) {
            $props{'Minute'}  = $props{'EveryMinute'};
        }
        if ( ! $props{'Hour'} && ($props{'EveryHour'} ne 'disabled' )) {
            $props{'Hour'}  = $props{'EveryHour'};
        }
        if ( ! $props{'Day'} && ($props{'EveryDay'} ne 'disabled' )) {
            $props{'Day'}  = $props{'EveryDay'};
        }
        if ( ! $props{'Month'} && ($props{'EveryMonth'} ne 'disabled' )) {
            $props{'Month'}  = $props{'EveryMonth'};
        }
        if ( ! $props{'WeekDay'} && ($props{'EveryWeekDay'} ne 'disabled' )) {
            $props{'WeekDay'}  = $props{'EveryWeekDay'};
        }

        push(@crontab, \%props);
    }
    $ret->{'crontab'} = \@crontab;

} else {
    NethServer::ApiTools::error();
}

print encode_json($ret);
